# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyCloudMusic' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for MyCloudMusic
  pod "QMUIKit"
  pod "MyLayout"
  pod "R.objc"
  pod "GKCycleScrollView"
  pod "MSNetwork"
  pod "AFNetworking"
  pod "YYCache"
  pod "MJExtension"
  pod "MBProgressHUD"
  pod "SDWebImage"
  pod "QTEventBus"
end
